# Generated by Django 3.1.4 on 2021-03-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_street_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Everyday_Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
